apiVersion: v1
kind: Service
metadata:
  name: baet-api-js
  labels:
    app: baet-api-js
    lang: node-js
    env: prod
spec:
  # use NodePort here to be able to access a port on each node
  type: NodePort
  ports:
    - port: 4042
  selector:
    app: baet-api-js
